name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build-production:
    name: Build Production Image
    runs-on: ubuntu-20.04

    env:
      CONTAINER_REGISTRY: docker.pkg.github.com
      CONTAINER_IMAGE: docker.pkg.github.com/geoffphillips/geoffmphillips/node-server
      COMMIT_SHA: ${{ github.sha }}
      REGISTRY_USER: geoffphillips
      REGISTRY_KEY: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build Image
        env:
          CONTAINER_TAG: latest
        run: |
          docker login -u="$REGISTRY_USER" -p="$REGISTRY_KEY" $CONTAINER_REGISTRY
          bash $GITHUB_WORKSPACE/ops/build/run.sh -p
  
  deploy-production:
    name: Deploy to Production
    runs-on: ubuntu-20.04
    needs: build-production

    env:
      CONTAINER_REGISTRY: docker.pkg.github.com
      CONTAINER_IMAGE: docker.pkg.github.com/geoffphillips/geoffmphillips/node-server
      COMMIT_SHA: ${{ github.sha }}
      REGISTRY_USER: geoffphillips
      REGISTRY_KEY: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Deploy
        env:
          APP_NAME: node_server
          DOKKU_SSH_HOST: ${{ secrets.DOKKU_PROD_SSH_HOST }}
          DOKKU_SSH_KEY: ${{ secrets.DOKKU_PROD_SSH_KEY }}
        run: |
          eval $(ssh-agent -s)
          echo "$DOKKU_SSH_KEY" | ssh-add -
          mkdir -p ~/.ssh
          ssh-keyscan $DOKKU_SSH_HOST >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts
          ssh dokku@DOKKU_SSH_HOST "docker-direct login $CONTAINER_REGISTRY -u $REGISTRY_USER -p $REGISTRY_KEY"
          ssh dokku@DOKKU_SSH_HOST "docker-direct pull $CONTAINER_IMAGE:$COMMIT_SHA"
          ssh dokku@DOKKU_SSH_HOST "docker-direct tag $CONTAINER_IMAGE:$COMMIT_SHA dokku/$APP_NAME:latest"
          ssh dokku@DOKKU_SSH_HOST "tags:deploy $APP_NAME latest"